### ISSUE TITLE
Map out structure of domzgr.F90

### ISSUE THREAD

**Issue by jdha** [pyNEMO/pyDOMCFG#2]
Produce skeleton of domzgr.F90 routines to _hang_ the python package on.

**Comment by oceandie** [comment]
As Mattia noted, we're not going to upload NEMO code on GitHub - so doc for FORTRAN DOMAINcfg needs to be generated only once. He suggests to put it into pyDOMCFG/docs/_static (maskes sense to me as well) and then just add a reference to it (I am not sure I understand this correctly - you mean in the index?).

Mattia also asked about graphviz, since there is an extension for sphinx: https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html: Would a single .dot file work or we need an html tree?

The .dot file can be embedded using:
.. graphviz:: external.dot

I checked and when running doxygen with graphviz no *.dot files are produced - so I think we might discard this option ....

**Comment by malmans2** [comment]
Actually, let me check if there's some kind of extension, because if you just link to the FORTRAN index.html then I doubt all links will work...

**Comment by malmans2** [comment]
Nevermind, maybe it just works.
I would try to place the DOMAINcfg html directory under static, then use a link that opens a new tab. For example, use something like this this to define the link
```
.. |DOMAINcfg_link| raw:: html

   <a href="./_static/DOMAINcfg_html/index.html" target="_blank">NEMO4.0.4-DOMAINcfg tool call tree</a>
```
then you can show the reference with:
```
|DOMAINcfg_link|
```

I guess you could either place the link in our `docs/index.rst`, or create a separate `.rst` with a few words about it under `docs/developers`

**Comment by oceandie** [comment]
Naive question: why the doc (https://pydomcfg.readthedocs.io/en/latest/) is not updated with my last merged modfications?

**Comment by malmans2** [comment]
I can see the call graph. Did you try to force refresh?
